load_path: 'query_data'
resume_label_path: 'labeled_data/resume_label_data.json'
label_resume_path: 'labeled_data/label_resume_data.json'

edu:
  template: ['具有%学历', '有%学历', '要求%学历', '要求有%学历', '具有%以上学历', 有%以上学历', 获得%以上学位', 要求至少有%以上学历', 拥有%学历']
  dict: ['高中', '专科', '本科', '全日制本科', '一本', '硕士', '硕士研究生', '研究生', '博士', '博士研究生']
  prob: [0.05, 0.05, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1,0.05, 0.05]

rank:
  template: ['%以上', '%以上干部', '担任过%以上干部', '%或以上干部', '%(及以上)', '%干部(及以上)']
  dict: [None, '副科级', '正科级', '副处级', '正处级', '副局级', '正局级', '副部级', '正部级']
  prob: [0.3, 0.25, 0.25, 0.05, 0.05, 0.03, 0.03, 0.02, 0.02]

age:
  template: ['%*', '%岁*', '要求%*', '要求%岁*']
  dict: ['25', '30', '35', '40', '45', '50', '55']
  condition: ['以上', '以下']