load_path: 'temp/query'
resume_label_path: 'labeled_data/resume_label_data.json'
label_resume_path: 'labeled_data/label_resume_data.json'
entity_dict_path: 'labeled_data/entity_dict.json'

edu:
  template: ['具有%学历', '有%学历', '要求%学历', '要求有%学历', '具有%以上学历', '有%以上学历', '获得%以上学位', '要求至少有%以上学历', '拥有%学历']
  dict: {'高中': '高中', '专科': '专科', '本科': '本科', '全日制本科': '本科', '一本': '本科', '硕士': '硕士', '硕士研究生': '硕士', '研究生': '硕士', '博士': '博士', '博士研究生': '博士'}
  prob: [0.05, 0.05, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05]

rank:
  generate: [0.5, 0.5]
  template: ['%以上', '%以上干部', '担任过%以上干部', '%或以上干部', '%(及以上)', '%干部(及以上)']
  dict: ['副科级', '正科级', '副处级', '正处级', '副局级', '正局级', '副部级', '正部级']
  prob: [0.3, 0.3, 0.15, 0.15, 0.03, 0.03, 0.02, 0.02]

gender:
  generate: [0.25, 0.75]
  template: ['要求%', '%优先']
  dict: ['男性', '女性']
  prob: [0.5, 0.5]

age:
  generate: [0.75, 0.25]
  template: ['%*', '%岁*', '要求%*', '要求%岁*']
  dict: ['25', '30', '35', '40', '45', '50', '55']
  condition: ['以上', '以下']
  prob: [0.1, 0.2, 0.2, 0.2, 0.1, 0.1, 0.1]

work_exp:
  nums: [1, 2]
  prob: [0.3, 0.7]
  template: ['具有#相关工作经历', '具有%年*#相关工作经历', '具有%年*#相关工作经验', '有#相关工作经历', '有#相关工作经验', '有%年*#相关工作经历', '有%年*#相关工作经验', '有%年*#工作经历', '%年*#工作经历', '%年*#相关工作经验']
  label_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
  label_prob: [0.02, 0.03, 0.08, 0.03, 0.05, 0.03, 0.02, 0.02, 0.02, 0.09, 0.04, 0.02, 0.02, 0.08, 0.02, 0.02, 0.02, 0.02, 0.12, 0.03, 0.02, 0.03, 0.02, 0.02, 0.04, 0.03, 0.02, 0.02, 0.02]
  time: {'3': 3, '三': 3, '2': 2, '两': 2, '二': 2, '5': 5, '五': 5, '4': 4, '四': 4, '1': 1, '一': 1}
  time_condition: ['以上', '以下']